### PR TITLE
Jupysql integration

### PR DESCRIPTION
**Pull request by idomic**
Adding jupysql into the Jupyter guide.
Additional example for plotting on top of DuckDB.

### CODE REVIEW

**Comment by idomic** [comment]
@Alex-Monahan ready for review!

**Comment by idomic** [comment]
ping

**Comment by Alex-Monahan** [comment]
> ping

Howdy! It's part of my plan for today! I had bucketed today as part of the weekend since it is a US holiday.

**Comment by idomic** [comment]
@Alex-Monahan looks great! Pretty neat feature, will definitely use it and provide feedback!
I think this is ready to go.

**Comment by idomic** [comment]
Do we wait for a release to see it in the docs?

**Comment by Mause** [comment]
> Do we wait for a release to see it in the docs?

we should only have to wait for the deploy, but it looks like the deploy is broken somehow - i'm looking into it

**Comment by Mause** [comment]
Should be up now! The deploy failure was GitHub having issues

**Pull request merged**
