### PR TITLE
Secondary menu should point to stable release

### LINKED ISSUE #940: Secondary menu should point to stable documentation
#912 changes the "Documentation" button of the front page to point to stable but the secondary menu (i.e. top bar) still points to the `dev` documentation.

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #940

### CODE REVIEW

**Comment by carlopi** [comment]
Even after this, there are plenty of navigation patterns that will still lead to seeing /docs, given it's the default everywhere, example: internal links to https://duckdb.org/docs/installation/.

If we want to have people browser stable docs by default, then I think the proper steps would be move /docs/ to /docs/next/, and then /docs/archive/v0.8.1 to /docs/.

That would ensure all links (internals AND external) point to stable docs.

Then on releases, /docs/ could go to /docs/archive/v0.8.1, /docs/next copied over to /docs, and on we go.

**Comment by szarnyasg** [comment]
Good point. However, I don't like the slug `next/` very much. Some alternatives: `snapshot` (sounds Java-ish to me), `dev` (is already used for the dev documentation),`latest`. WDYT?

**Comment by Mause** [comment]
Maybe `nightly`?

**Comment by szarnyasg** [comment]
I feel like nightly has gone out of fashion somewhat. I checked Postgres and it uses `current`, which I quite like:
https://www.postgresql.org/docs/current/

**Comment by Mause** [comment]
Yeah about that: https://github.com/duckdb/duckdb-web/pull/544

**Comment by szarnyasg** [comment]
Haha, okay. Naming things is hard.

**Comment by szarnyasg** [comment]
I spun up the naming discussion into an issue at #960, so we can focus on the PR here. Let me know whether this is good the merge.

**Pull request merged**
