### PR TITLE
Clarify multiprocess read/write support

### PR DESCRIPTION
**Pull request by davetapley**
Is still confusing people, see e.g.:
https://github.com/duckdb/duckdb/issues/77
https://github.com/duckdb/duckdb/issues/5317

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Great thought! I'm going to add an FAQ entry for it. I think it deserves some extra explanation!

**Comment by pbowyer** [comment]
> Great thought! I'm going to add an FAQ entry for it. I think it deserves some extra explanation!

Definitely. As a potential user it's a real "gotcha" when coming from sqlite or any DB. Not having concurrent writes I get, but having read #77 why there's the inability to read when there's a writer connected or vice versa is still a mystery, if the writes are going to the WAL.

**Comment by Alex-Monahan** [comment]
> > Great thought! I'm going to add an FAQ entry for it. I think it deserves some extra explanation!
> 
> Definitely. As a potential user it's a real "gotcha" when coming from sqlite or any DB. Not having concurrent writes I get, but having read #77 why there's the inability to read when there's a writer connected or vice versa is still a mystery, if the writes are going to the WAL.

Ah, so the reason for that is in the case where the WAL checkpoints (inserts into the DB and then clears out the WAL). Handling that situation gracefully in the multiprocess case is not trivial.

**Comment by Alex-Monahan** [comment]
Thanks again for the PR! I also added some information in the FAQ for more details. https://duckdb.org/faq

**Pull request merged**
