### PR TITLE
Document query_* functions

### LINKED ISSUE #2100: [duckdb/#10586] - add query() function needs documentation
See https://github.com/duckdb/duckdb/issues/10586

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #2100

### CODE REVIEW

**Comment by szarnyasg** [comment]
@chrisiou for the `TABLE_REF query_table(VARCHAR tbl_name [, BOOLEAN by_name])` funtion, what is the effect of the setting the `by_name` parameter to `true`?

**Comment by chrisiou** [comment]
> @chrisiou for the `TABLE_REF query_table(VARCHAR tbl_name [, BOOLEAN by_name])` funtion, what is the effect of the setting the `by_name` parameter to `true`?

When the `by_name` parameter is set to `true`, it"unions" all tables `BY NAME` (as [union_all](https://github.com/duckdb/duckdb/pull/10586#issuecomment-1951571760) does).

**Comment by chrisiou** [comment]
> @chrisiou for the `TABLE_REF query_table(VARCHAR tbl_name [, BOOLEAN by_name])` funtion, what is the effect of the setting the `by_name` parameter to `true`?

ooh, actually this parameter does not affect the function in any way. I just removed it! :grimacing:
So now, it is: 

```
TABLE_REF query_table(VARCHAR tbl_name)
```

**Comment by szarnyasg** [comment]
I am reworking all tables in the documentation by turning them into two-column tables with a separate sections for each function. Therefore, I'm parking this PR and will revisit it later once 1) the tables have been reformatted 2) the `query_*` functions have been merged.

**Pull request closed without merging**
