### PR TITLE
Fugue with DuckDB

### PR DESCRIPTION
**Pull request by kvnkho**
Documenting usage of Fugue with DuckDB

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Looks good! I'm going to make a small tweak or two, and create a Google Collab notebook so that folks can see your Jupyter extension.

**Comment by Alex-Monahan** [comment]
How does this look for a basic collab example? Other things you would add? 
https://colab.research.google.com/drive/10J84_Ydq6NdYUqOOSidN495ERfwZ6N4_?usp=share_link

**Comment by kvnkho** [comment]
> How does this look for a basic collab example? Other things you would add? https://colab.research.google.com/drive/10J84_Ydq6NdYUqOOSidN495ERfwZ6N4_?usp=share_link

Ah I see thanks for that! FugueSQL should works there but the highlighting does not because Google Colab uses a really old version of ipykernel. 

I don't know how minimal you want it to be but all the snippets I posted should work on the notebook. It's just a matter of what you want to include :)

**Comment by kvnkho** [comment]
Ah sorry I have one note. We are actually deprecating `fugue_notebook` in favor of `fugue_jupyter`. You can do `from fugue_jupyter import setup`

**Comment by Alex-Monahan** [comment]
I'll take a shot at resolving the merge conflicts tomorrow to get this merged! Thanks for your work on this!

**Pull request merged**
