### PR TITLE
generate robots.txt to exclude old archives from being indexed

### PR DESCRIPTION
**Pull request by Mause**
Fixes https://github.com/duckdb/duckdb-web/issues/1806

~~Might be worth updating our search index generation as well~~

### CODE REVIEW

**Review by szarnyasg — APPROVED** [review]

**Comment by szarnyasg** [comment]
I ran it locally and it this gives me the following `robots.txt` file:
```
Sitemap: https://duckdb.org/sitemap.xml

User-agent: *

Allow: /
```

**Comment by Mause** [comment]
> I ran it locally and it this gives me the following `robots.txt` file:
> ```
> Sitemap: https://duckdb.org/sitemap.xml
> 
> User-agent: *
> 
> Allow: /
> ```

Did you run it in archive exclude mode?

**Comment by szarnyasg** [comment]
No, I ran it using `scripts/serve.sh` which generates the full website. I pushed a new version which produces this locally:
```txt
Sitemap: https://duckdb.org/sitemap.xml

User-agent: *

Disallow: /docs/archive/0.9.1
Disallow: /docs/archive/0.9.0
Disallow: /docs/archive/0.8.1
Disallow: /docs/archive/0.7.1
Disallow: /docs/archive/0.6.1
Disallow: /docs/archive/0.5.1
Disallow: /docs/archive/0.4.0
Allow: /
```

**Comment by Mause** [comment]
> No, I ran it using `scripts/serve.sh` which generates the full website. I pushed a new version which produces this locally:
> 
> ```
> Sitemap: https://duckdb.org/sitemap.xml
> 
> User-agent: *
> 
> Disallow: /docs/archive/0.9.1
> Disallow: /docs/archive/0.9.0
> Disallow: /docs/archive/0.8.1
> Disallow: /docs/archive/0.7.1
> Disallow: /docs/archive/0.6.1
> Disallow: /docs/archive/0.5.1
> Disallow: /docs/archive/0.4.0
> Allow: /
> ```

Yep, looks good now - might have to tweak it further (maybe test it with some Google tooling), but let's see how it goes?

**Pull request merged**
