### PR TITLE
Add caveat for FTS index

### PR DESCRIPTION
**Pull request by patrickpang**
As a follow-up of https://github.com/duckdb/duckdb/issues/3543

### CODE REVIEW

**Comment by hannes** [comment]
Thanks for adding the note, but don't you think immediately after the initial sentence is a bit early for this?

**Comment by patrickpang** [comment]
I see. How about A separate caveat section in the end?

**Comment by Alex-Monahan** [comment]
Looks fine to me!

**Comment by patrickpang** [comment]
Thank you!

**Pull request merged**
