### PR TITLE
Update interval.md

### PR DESCRIPTION
**Pull request by soerenwolfers**

### CODE REVIEW

**Comment by soerenwolfers** [comment]
don't merge just yet, more typos

**Comment by soerenwolfers** [comment]
@szarnyasg  Good to go.

**Comment by szarnyasg** [comment]
Great, thanks!

**Comment by soerenwolfers** [comment]
@szarnyasg Btw, is there automated tooling to make sure the function descriptions in the "summary tables" matches the "detail tables", e.g., at https://duckdb.org/docs/sql/functions/interval.html#date_partpart-interval ? 

Having to update two places is error-prone and slightly tedious.

**Comment by szarnyasg** [comment]
@soerenwolfers It is indeed both tedious and error-prone. There's no tooling yet but we are working on automating this and generating most of the content from code.

**Pull request merged**
