### PR TITLE
Update unnest.md

### PR DESCRIPTION
**Pull request by soerenwolfers**
https://github.com/duckdb/duckdb-web/issues/2782

### CODE REVIEW

**Comment by soerenwolfers** [comment]
I am not sure what the `:` in the markdown tables does (it's missing from my table). If it's necessary, is there a way to auto-generate a table that conforms with the documentation requirements from the duckdb CLI?

**Comment by szarnyasg** [comment]
Hi @soerenwolfers, the `:` sets the horizontal alignment of the table column. Since 0.10.1, `.mode markdown` applies this for numeric columns.
~/duckdb/0.10.1/duckdb
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .mode markdown
D SELECT unnest(l) as x, generate_subscripts(l, 1) AS index FROM (VALUES ([1, 2, 3]), ([4, 5])) tbl(l);
| x | index |
|--:|------:|
| 1 | 1     |
| 2 | 2     |
| 3 | 3     |
| 4 | 1     |
| 5 | 2     |

**Comment by soerenwolfers** [comment]
Oh, this just made me realize that my CLI is not updated when I update my Python package.

**Comment by szarnyasg** [comment]
Right. This has been a recurring report from users, so I'm going to open a new issue for this.

**Pull request merged**
