### PR TITLE
Update timestamp.md

### PR DESCRIPTION
**Pull request by manticore-projects**
Add `CURRENT_TIMESTAMP` to the list

### CODE REVIEW

**Comment by szarnyasg** [comment]
Thanks!

**Comment by hayssams** [comment]
Looks like calling current_timestamp() does not work. 
```
$ duckdb
v0.10.1 4a89d97db8
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select current_timestamp();
Catalog Error: Scalar Function with name current_timestamp does not exist!
Did you mean "get_current_timestamp"?
LINE 1: select current_timestamp()
               ^
D select current_date() ;
┌────────────────┐
│ current_date() │
│      date      │
├────────────────┤
│ 2024-04-16     │
└────────────────┘
D 
```

**Comment by Mause** [comment]
It's not a function, it's a magic value (which should probably be explicitly called out in the docs)

**Comment by manticore-projects** [comment]
Thank you for quick roundturn.

```sql
-- works
select current_date=current_date();

-- fails and I think the function should be added just for consistency
select current_timestamp=current_timestamp();
```

**Comment by manticore-projects** [comment]
> It's not a function, it's a magic value (for lack of a better term, which should probably be explicitly called out in the docs)

@Mause: in my limited understanding, it should be foremost a `Function()` because it returns a system value, which then can be abbreviated by a "magic value" (which I would call a Time Key Expression).

**Pull request merged**
