### PR TITLE
Cleanup/convert some large files

### PR DESCRIPTION
**Pull request by szarnyasg**

### CODE REVIEW

**Review by Mause — CHANGES_REQUESTED** [review]
Why convert these files? ~~Why commit the pickle files?~~ my bad, you deleted them instead

**Comment by szarnyasg** [comment]
The PNGs were huge (the Jason duck PNG was ~5MB) and quality difference isn't noticeable when converted to JPG.
We could also revisit issue #218 in the near future.

**Comment by Mause** [comment]
> The PNGs were huge (the Jason duck PNG was ~5MB) and quality difference isn't noticeable when converted to JPG. We could also revisit issue #218 in the near future.

Maybe we should leave these files as is to test out imgbot?

**Comment by szarnyasg** [comment]
I doubt imgbot will convert from PNG to JPG (which was the trick here). I'll add imgbot in a moment but it will not resolve this.

**Comment by szarnyasg** [comment]
Update: setting up imgbot requires owner permissions, which I don't have:
https://github.com/marketplace/imgbot/plan/MLP_kgDNGw8#pricing-and-setup

**Review by Mause — APPROVED** [review]

**Pull request merged**
