### PR TITLE
feat: document storage info

### LINKED ISSUE #177: Document the `storage_info` pragma
Hey folks!

On Discord, @hannes mentioned the `storage_info` pragma as a way to get the storage footprint of a table:

```sql
PRAGMA storage_info('my_table');
```

The columns provide a ton of info:

```
row_group_id,
column_name,
column_id,
column_path, 
segment_id,
segment_type,
start,
count, 
compression,
stats,
has_updates,
persistent,
block_id,
block_offset
```

I'm looking to calculate the storage size of a table, so I assume that means summing `count` here.

This would be an awesome pragma to document if possible! Very useful for those of us telling the machine to do a lot of big calculations in DuckDB.

### PR DESCRIPTION
**Pull request by Mause**
Fixes #177 
Fixes https://github.com/duckdb/duckdb/discussions/5730

### CODE REVIEW

**Comment by Tishj** [comment]
We could also make the storage version read a function on the `duckdb` module
`duckdb.storage_version()` -> return storage version of current latest version
`duckdb.storage_version(file_name)` -> try to run the code you listed as example, throwing an exception if the input is invalid

**Comment by Mause** [comment]
> We could also make the storage version read a function on the `duckdb` module `duckdb.storage_version()` -> return storage version of current latest version `duckdb.storage_version(file_name)` -> try to run the code you listed as example, throwing an exception if the input is invalid
> 
> What do you think?

What's the usecase you envision with those?

**Comment by Mytherin** [comment]
> We could also make the storage version read a function on the `duckdb` module `duckdb.storage_version()` -> return storage version of current latest version `duckdb.storage_version(file_name)` -> try to run the code you listed as example, throwing an exception if the input is invalid
> 
> What do you think?

I was thinking about adding this list to DuckDB internally and having it report the DuckDB version when opening an old file.

**Comment by Mause** [comment]
> > We could also make the storage version read a function on the `duckdb` module `duckdb.storage_version()` -> return storage version of current latest version `duckdb.storage_version(file_name)` -> try to run the code you listed as example, throwing an exception if the input is invalid
> > 
> > What do you think?
> 
> I was thinking about adding this list to DuckDB internally and having it report the DuckDB version when opening an old file.

Do you mean without having to parse it from the error message?

https://github.com/duckdb/duckdb/blob/16f362852baeb64e6a725eac12a9d45982d40901/src/storage/single_file_block_manager.cpp#L156-L165

**Comment by Mytherin** [comment]
Yes, exactly.

**Comment by Mause** [comment]
I think it would still be worth having this documented regardless?

**Comment by Mytherin** [comment]
Yes, for sure

**Comment by Mytherin** [comment]
Sure, I have pushed a minor fix, otherwise this looks good to me.

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
