### PR TITLE
Bump community extensions MD

### PR DESCRIPTION
**Pull request by carlopi**

### CODE REVIEW

**Comment by szarnyasg** [comment]
@carlopi the build is failing: it needs the `.md` in the Jekyll links.

**Comment by carlopi** [comment]
> @carlopi the build is failing: it needs the `.md` in the Jekyll links.

very important question, but how to make it so when clicking on the list it will not go to `path/to/page.html` but to `path/to/page` ?

**Comment by carlopi** [comment]
Done the link -> md fix.

**Comment by szarnyasg** [comment]
Thanks!

**Pull request merged**
