### PR TITLE
Fix docker local build

### PR DESCRIPTION
**Pull request by quentingodeau**
Fix missing header (linux/limits.h)
Fix wrong permission (cannot write Gemfile.lock)

### CODE REVIEW

**Comment by szarnyasg** [comment]
Thanks, I'll test it. Are you using Linux?
MacOS' Docker is [more lenient with permissions](https://stackoverflow.com/questions/61009190/docker-mount-permissions-on-mac-vs-linux/61009413#61009413), so I may have been able to get away with sloppy settings.

**Comment by szarnyasg** [comment]
For me,
```bash
scripts/docker-build.sh
```
now fails with:
```
18.79 An error occurred while installing ffi (1.16.3), and Bundler cannot continue.
18.79
18.79 In Gemfile:
18.79   github-pages-health-check was resolved to 1.18.2, which depends on
18.79     typhoeus was resolved to 1.4.1, which depends on
18.79       ethon was resolved to 0.16.0, which depends on
18.79         ffi
------
Dockerfile:9
--------------------
   7 |
   8 |     RUN apk add --update gcc g++ make ruby-bundler
   9 | >>> RUN cd /app && bundle install
  10 |
  11 |     EXPOSE 4000
ERROR: failed to solve: process "/bin/sh -c cd /app && bundle install" did not complete successfully: exit code: 5
```

Do you have any insight on why that may happen?

**Comment by szarnyasg** [comment]
Scratch that, I was on the wrong branch.

**Comment by quentingodeau** [comment]
Hi,

Just some feedback here, I spend so much time trying/fixing the docker build to be able to see the rendering than writing the documentation that I almost give up :(

Maybe I have done something wrong I don't known but I just wanted to make it work...

 To summaries my journey:

1. I got a compilation header:
   ```text
   ./scripts/docker-build.sh
   +++ dirname ./scripts/docker-build.sh
   ++ cd ./scripts
   ++ pwd
   + cd /home/quentin/gitws/duckdb-web/scripts/..
   + . scripts/docker-vars.sh
   ++ JEKYLL_DOCKER_IMAGE_NAME=duckdb-web-jekyll-img
   ++ JEKYLL_DOCKER_CONTAINER_NAME=duckdb-web-jekyll
   + docker build . --tag duckdb-web-jekyll-img
   [+] Building 43.2s (10/10) FINISHED                                                                                                                                                                                                                        docker:default
    => [internal] load build definition from Dockerfile                                                                                                                                                                                                                 0.0s 
    => => transferring dockerfile: 242B                                                                                                                                                                                                                                 0.0s
    => [internal] load .dockerignore                                                                                                                                                                                                                                    0.0s 
    => => transferring context: 76B                                                                                                                                                                                                                                     0.0s 
    => [internal] load metadata for docker.io/rockstorm/jekyll:pages-v228-minimal                                                                                                                                                                                       1.5s 
    => [1/6] FROM docker.io/rockstorm/jekyll:pages-v228-minimal@sha256:c60506da0222300cdb2a68e5a3372743b64591377c503dae6a4909a8efc0a8e5                                                                                                                                 0.0s
    => [internal] load build context                                                                                                                                                                                                                                    0.0s 
    => => transferring context: 61B                                                                                                                                                                                                                                     0.0s 
    => CACHED [2/6] RUN mkdir /app                                                                                                                                                                                                                                      0.0s 
    => CACHED [3/6] COPY Gemfile /app                                                                                                                                                                                                                                   0.0s 
    => CACHED [4/6] COPY Gemfile.lock /app                                                                                                                                                                                                                              0.0s 
    => CACHED [5/6] RUN apk add --update gcc g++ make ruby-bundler                                                                                                                                                                                                      0.0s 
    => ERROR [6/6] RUN cd /app && bundle install                                                                                                                                                                                                                       41.6s 
   ------
    > [6/6] RUN cd /app && bundle install:
   29.69 Bundler 2.4.6 is running, but your lockfile was generated with 2.5.4. Installing Bundler 2.5.4 and restarting using that version.
   30.71 Fetching gem metadata from https://rubygems.org/.
   30.75 Fetching bundler 2.5.4
   30.88 Installing bundler 2.5.4
   31.55 Fetching gem metadata from https://rubygems.org/...........
   33.67 Fetching https://github.com/duckdb/rouge.git
   35.92 Fetching public_suffix 5.0.4
   35.97 Fetching execjs 2.9.1
   36.05 Installing execjs 2.9.1
   36.05 Installing public_suffix 5.0.4
   36.06 Fetching commonmarker 0.23.10
   36.06 Fetching concurrent-ruby 1.2.3
   36.10 Installing commonmarker 0.23.10 with native extensions
   36.13 Installing concurrent-ruby 1.2.3
   36.15 Fetching unf_ext 0.0.9.1
   36.18 Installing unf_ext 0.0.9.1 with native extensions
   36.93 Fetching ffi 1.16.3
   37.00 Installing ffi 1.16.3 with native extensions
   40.09 Fetching uri 0.13.0
   40.15 Installing uri 0.13.0
   40.15 Fetching rexml 3.2.6
   40.19 Installing rexml 3.2.6
   40.20 Fetching posix-spawn 0.3.15
   40.22 Installing posix-spawn 0.3.15 with native extensions
   40.48 Fetching word_wrap 1.0.0
   40.50 Installing word_wrap 1.0.0
   40.50 Fetching addressable 2.8.6
   40.53 Installing addressable 2.8.6
   40.54 Fetching i18n 1.14.1
   40.56 Installing i18n 1.14.1
   40.57 Fetching net-http 0.4.1
   40.59 Installing net-http 0.4.1
   40.60 Fetching faraday-net_http 3.1.0
   40.62 Installing faraday-net_http 3.1.0
   40.62 Fetching dnsruby 1.70.0
   40.67 Installing dnsruby 1.70.0
   40.68 Fetching faraday 2.9.0
   40.71 Installing faraday 2.9.0
   41.53 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
   41.53
   41.53     current directory: /usr/gem/gems/ffi-1.16.3/ext/ffi_c
   41.53 /usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/3.1.0 extconf.rb
   41.53 checking for ffi.h... no
   41.53 checking for ffi.h in
   41.53 /usr/local/include,/usr/include/ffi,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi...
   41.53 no
   41.53 checking for whether -Wl,--exclude-libs,ALL is accepted as LDFLAGS... yes
   41.53 checking for rb_gc_mark_movable()... yes
   41.53 checking for whether -pthread is accepted as LDFLAGS... yes
   41.53 creating extconf.h
   41.53 creating Makefile
   41.53
   41.53 current directory: /usr/gem/gems/ffi-1.16.3/ext/ffi_c
   41.53 make DESTDIR\= sitearchdir\=./.gem.20240223-23-nvuhsx
   41.53 sitelibdir\=./.gem.20240223-23-nvuhsx clean
   41.53
   41.53 current directory: /usr/gem/gems/ffi-1.16.3/ext/ffi_c
   41.53 make DESTDIR\= sitearchdir\=./.gem.20240223-23-nvuhsx
   41.53 sitelibdir\=./.gem.20240223-23-nvuhsx
   41.53 Configuring libffi
   41.53 make -C "/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl"
   41.53 make[1]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 make  all-recursive
   41.53 make[2]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 Making all in include
   41.53 make[3]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/include'
   41.53 make[3]: Nothing to be done for 'all'.
   41.53 make[3]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/include'
   41.53 Making all in testsuite
   41.53 make[3]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/testsuite'
   41.53 make[3]: Nothing to be done for 'all'.
   41.53 make[3]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/testsuite'
   41.53 Making all in man
   41.53 make[3]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/man'
   41.53 make[3]: Nothing to be done for 'all'.
   41.53 make[3]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl/man'
   41.53 make[3]: Entering directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/prep_cif.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/prep_cif.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/prep_cif.c  -fPIC -DPIC -o
   41.53 src/prep_cif.o
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/types.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/types.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/types.c  -fPIC -DPIC -o
   41.53 src/types.o
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/raw_api.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/raw_api.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/raw_api.c  -fPIC -DPIC -o
   41.53 src/raw_api.o
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/java_raw_api.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c  -fPIC -DPIC -o
   41.53 src/java_raw_api.o
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c: In function
   41.53 'ffi_java_raw_call':
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:317:3: warning:
   41.53 'ffi_java_raw_to_ptrarray' is deprecated [-Wdeprecated-declarations]
   41.53   317 |   ffi_java_raw_to_ptrarray (cif, raw, avalue);
   41.53       |   ^~~~~~~~~~~~~~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:76:1: note:
   41.53 declared here
   41.53    76 | ffi_java_raw_to_ptrarray (ffi_cif *cif, ffi_java_raw *raw, void **args)
   41.53       | ^~~~~~~~~~~~~~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c: In function
   41.53 'ffi_java_translate_args':
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:328:3: warning:
   41.53 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
   41.53   328 |   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
   41.53       |   ^~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:45:1: note:
   41.53 declared here
   41.53    45 | ffi_java_raw_size (ffi_cif *cif)
   41.53       | ^~~~~~~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:331:3: warning:
   41.53 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
   41.53   331 |   ffi_java_ptrarray_to_raw (cif, avalue, raw);
   41.53       |   ^~~~~~~~~~~~~~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:157:1: note:
   41.53 declared here
   41.53   157 | ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw)
   41.53       | ^~~~~~~~~~~~~~~~~~~~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c: In function
   41.53 'ffi_prep_java_raw_closure':
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:369:3: warning:
   41.53 'ffi_prep_java_raw_closure_loc' is deprecated [-Wdeprecated-declarations]
   41.53   369 |   return ffi_prep_java_raw_closure_loc (cl, cif, fun, user_data, cl);
   41.53       |   ^~~~~~
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/java_raw_api.c:337:1: note:
   41.53 declared here
   41.53   337 | ffi_prep_java_raw_closure_loc (ffi_java_raw_closure* cl,
   41.53       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/closures.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/closures.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/closures.c  -fPIC -DPIC -o
   41.53 src/closures.o
   41.53 /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi  -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src   -Wall  -fexceptions -c -o
   41.53 src/tramp.lo /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/tramp.c
   41.53 libtool: compile:  gcc -DHAVE_CONFIG_H -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi -I.
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/include -Iinclude
   41.53 -I/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src -Wall -fexceptions -c
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/tramp.c  -fPIC -DPIC -o
   41.53 src/tramp.o
   41.53 /usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi/src/tramp.c:55:10: fatal error:
   41.53 linux/limits.h: No such file or directory
   41.53    55 | #include <linux/limits.h>
   41.53       |          ^~~~~~~~~~~~~~~~
   41.53 compilation terminated.
   41.53 make[3]: *** [Makefile:1341: src/tramp.lo] Error 1
   41.53 make[3]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 make[2]: *** [Makefile:1414: all-recursive] Error 1
   41.53 make[2]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 make[1]: *** [Makefile:627: all] Error 2
   41.53 make[1]: Leaving directory
   41.53 '/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl'
   41.53 make: *** [libffi.mk:9:
   41.53 "/usr/gem/gems/ffi-1.16.3/ext/ffi_c/libffi-x86_64-linux-musl"/.libs/libffi_convenience.a]
   41.53 Error 2
   41.53
   41.53 make failed, exit code 2
   41.53
   41.53 Gem files will remain installed in /usr/gem/gems/ffi-1.16.3 for inspection.
   41.53 Results logged to
   41.53 /usr/gem/extensions/x86_64-linux-musl/3.1.0/ffi-1.16.3/gem_make.out
   41.53
   41.53   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:51:in `block in
   41.53 make'
   41.53   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:43:in `each'
   41.53   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:43:in `make'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:42:in
   41.53 `build'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:170:in
   41.53 `build_extension'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:204:in `block in
   41.53 build_extensions'
   41.53   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:201:in `each'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:201:in
   41.53 `build_extensions'
   41.53 /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:843:in
   41.53 `build_extensions'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/rubygems_gem_installer.rb:76:in
   41.53 `build_extensions'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/rubygems_gem_installer.rb:28:in
   41.53 `install'
   41.53   /usr/gem/gems/bundler-2.5.4/lib/bundler/source/rubygems.rb:205:in `install'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/installer/gem_installer.rb:54:in
   41.53 `install'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/installer/gem_installer.rb:16:in
   41.53 `install_from_spec'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/installer/parallel_installer.rb:132:in
   41.53 `do_install'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/installer/parallel_installer.rb:123:in
   41.53 `block in worker_pool'
   41.53   /usr/gem/gems/bundler-2.5.4/lib/bundler/worker.rb:62:in `apply_func'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/worker.rb:57:in `block in
   41.53 process_queue'
   41.53   /usr/gem/gems/bundler-2.5.4/lib/bundler/worker.rb:54:in `loop'
   41.53   /usr/gem/gems/bundler-2.5.4/lib/bundler/worker.rb:54:in `process_queue'
   41.53 /usr/gem/gems/bundler-2.5.4/lib/bundler/worker.rb:90:in `block (2 levels) in
   41.53 create_threads'
   41.53
   41.53 An error occurred while installing ffi (1.16.3), and Bundler cannot continue.
   41.53
   41.53 In Gemfile:
   41.53   github-pages-health-check was resolved to 1.18.2, which depends on
   41.53     typhoeus was resolved to 1.4.1, which depends on
   41.53       ethon was resolved to 0.16.0, which depends on
   41.53         ffi
   ------
   WARNING: current commit information was not captured by the build: failed to read current commit information with git rev-parse --is-inside-work-tree
   Dockerfile:9
   --------------------
      7 |
      8 |     RUN apk add --update gcc g++ make ruby-bundler
      9 | >>> RUN cd /app && bundle install
     10 |
     11 |     EXPOSE 4000
   --------------------
   ERROR: failed to solve: process "/bin/sh -c cd /app && bundle install" did not complete successfully: exit code: 5
   
   View build details: docker-desktop://dashboard/build/default/default/usc0bnskyzuazl9gh2zjvjqmm
   ```
2. I got permission issues on the `Gemfile.lock` file (still during the installation part) (sorry close the terminal I do not have the logs here)
3. I got issue with volume mounting^^

**Comment by quentingodeau** [comment]
I'm using Windows with a WSL2 setup and docker install in the WSL without docker desktop

**Comment by szarnyasg** [comment]
Thanks for sharing your journey!

I initially created the Docker image because Jekyll required a Ruby version that was tricky to install on Apple Silicon Macs. This has been resolved now, so Mac users can now very easily [install Ruby and Jekyll](https://github.com/duckdb/duckdb-web/blob/main/BUILDING.md#using-a-local-jekyll-installation).

Of course, we'd like to keep the Docker container working on Mac too. Your Docker patch works fine for me on macOS, so I'll merge this patch.

**Pull request merged**
