### PR TITLE
Create scala.md

### PR DESCRIPTION
**Pull request by jim-tommaney**
Does it make sense to call out usage in Scala?

### CODE REVIEW

**Comment by Mytherin** [comment]
Looks good to me, but I don't have particularly strong opinions on anything related to Java. @hannesmuehleisen what do you think?

**Comment by Alex-Monahan** [comment]
Thanks for putting this together @jim-tommaney! I found a few small typos and just had a small question as well.

> Scala uses DuckDB's JDBC API implements the main parts of the standard Java Database Connectivity (JDBC) API, version 4.0. 
changes to:

> Scala uses DuckDB's JDBC API **which** implements the main parts of the standard Java Database Connectivity (JDBC) API, version 4.0. 

> you can use the custom duplicate() method like so:

Would you be able to describe what the duplicate function is doing to allow multiple read-write connections? That feature isn't possible through other DuckDB API's as far as I know, so it sounds very beneficial!

**Comment by jim-tommaney** [comment]
@Alex-Monahan 
Alex, 

I used the java doc as a template for scala, with needed net changes.
https://duckdb.org/docs/api/java


This came from the Java doc, and afaik should still be valid:

If you would like to create multiple read-write connections to the same database file or the same in-memory database instance, you can use the custom duplicate() method like so:

Connection conn2 = ((DuckDBConnection) conn).duplicate();

**Comment by Alex-Monahan** [comment]
Thank you for the explanation! It would be fine with me to merge now!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
