### PR TITLE
Add tldr field to blog posts' front matter

### PR DESCRIPTION
**Pull request by szarnyasg**

### CODE REVIEW

**Comment by Mause** [comment]
Shouldn't this already be handled by the excerpt?

**Comment by szarnyasg** [comment]
To some extent, but I'd like to make a clear separation and put the TL;DR to the front matter.

**Comment by szarnyasg** [comment]
The rationale is that we want nicer blog post pages with a TL;DR box at their beginning – see this sketch by Jonathan:

Screenshot 2024-02-06 at 16 48 00

**Comment by Mause** [comment]
We should probably use the name `excerpt` instead then, so it's used in the seo description

**Comment by szarnyasg** [comment]
Good point. Fix incoming ...

**Pull request merged**
