### PR TITLE
:tea: tea.xyz/+duckdb.org > Update installation.html > Add tea.xyz to install options

### PR DESCRIPTION
**Pull request by adriens**
# :grey_question: About

[`tea.xyz`](https://tea.xyz/) is a great way of : 

- :heavy_check_mark:  install software
- :heavy_check_mark:  using software without installing
- :heavy_check_mark:  keeping up-to-date very easily
- :heavy_check_mark:  Write easy tutorial oneliners to share code around duckdb

`duckdb` has recenlty been deployed into [`tea.xyz/+duckdb.org/`](https://tea.xyz/+duckdb.org/)

:point_right: Now, it just has to be added to install options :smile_cat: 

image

# :dart:  NB about PR

:point_up_2: I've added some code but due to my lack of Jekyll knowledge, **I was not able to add the following resources :** 

```shell
sh <(curl https://tea.xyz) +duckdb.org duckdb -version
```

```shell
sh <(curl https://tea.xyz) +duckdb.org duckdb -c 'select version()'
``` 

# :bookmark: Related resources

- https://github.com/duckdb/duckdb/discussions/6721
- https://github.com/teaxyz/pantry/issues/787
- https://github.com/teaxyz/pantry/issues/780
- https://tea.xyz/
- https://tea.xyz/+duckdb.org/

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Thank you for adding it to tea and for your work on the docs! 

However, I'm not sure we want to add it to the official installation page. We don't maintain the tea package and likely don't want to sign up for maintaining it over there. There are multiple other community maintained DuckDB libraries (like in Rust, etc.) that aren't on our installation page since we don't maintain them directly.

@Mause - do you have any thoughts here? You are a package maintainer and I am not, so I value your input! Maybe the solution is just to add everything (Rust, Go, etc.) and have disclaimers that they are community maintained?

**Comment by Mause** [comment]
I think for now, given this is a fairly new and not widely known package manager (I haven't heard of before SALES created an issue mentioning it), we can leave this out of the docs. People that are already using tea will know to check if it's available there, and if in the future it gains popularity, we can revisit it then

**Comment by adriens** [comment]
> Maybe the solution is just to add everything (Rust, Go, etc.) and have disclaimers that they are community maintained?

Yes, having a contributors like page would be really cool, same remark for extenstions BtW :thought_balloon: 

> (I haven't heard of before SALES created an issue mentioning it),

:bulb:  In fact it's the successor of `brew`

**Comment by adriens** [comment]
hi @Alex-Monahan , I was thinking about a dedicated  contributor section with subsections for : 

- extensions
- package installs made by contributors
- show & tells
- [Gh Actions](https://github.com/marketplace/actions/duckdb-setup)

It should make content easier to read, I guess :smile_cat:

**Comment by Mause** [comment]
> hi @Alex-Monahan , I was thinking about a dedicated contributor section with subsections for :
> 
> * extensions
> * package installs made by contributors
> * show & tells
> * [Gh Actions](https://github.com/marketplace/actions/duckdb-setup)
> 
> It should make content easier to read, I guess 😸

We should probably add a section like this yes. In the meantime, I'll close this though

**Pull request closed without merging**
