### PR TITLE
Returning clause of insert statement

### PR DESCRIPTION
**Pull request by Alex-Monahan**

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Oh, the PR had a comment that it was only inserts. Maybe it was enhanced midway through the PR's revisions?

**Review by hawkfish — APPROVED** [review]

**Comment by Mause** [comment]
@Alex-Monahan is there anything blocking this getting merged? Would be great to be able to point to the docs for this

**Comment by Alex-Monahan** [comment]
Nothing blocking, just a todo for delete and update statements (that could be a separate issue)

**Comment by Mytherin** [comment]
Let’s merge this then and deal with the other statements separately

**Pull request merged**
