### PR TITLE
feat: update config docs

### PR DESCRIPTION
**Pull request by Mause**
Looks like the default values for `enable_profiling` and `profiling_mode` have changed?

### CODE REVIEW

**Comment by Mytherin** [comment]
Could we perhaps work towards creating a single script that updates all of the docs, which we can then be run once as part of the release+archive cycle?

**Comment by Mause** [comment]
> Could we perhaps work towards creating a single script that updates all of the docs, which we can then run once as part of the release+archive cycle?

I think being able to run them individually has it's merits, but happy to add a script that's just calls them all?

**Comment by Mytherin** [comment]
Yes, that sounds great

**Comment by Mause** [comment]
@Mytherin added here: https://github.com/duckdb/duckdb-web/pull/278/files#diff-12f4513287b674b88d7f3fb3365952db1682a45159884ac044f21b7e7b337ae5

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
