### PR TITLE
Remove Discord ribbon

### PR DESCRIPTION
**Pull request by szarnyasg**
Remove the Discord ribbon.

### CODE REVIEW

**Comment by Mause** [comment]
Rationale?

**Comment by szarnyasg** [comment]
Occupies prime real estate on the landing page. We'd like to redesign the landing with nicer graphics, demo, etc. in the coming weeks.

**Comment by Mause** [comment]
> Occupies prime real estate on the landing page. We'd like to redesign the landing with nicer graphics, demo, etc. in the coming weeks.

Reasonable. Can you revert the original pr instead though, there's js attached to the feature too

**Review by Mause — CHANGES_REQUESTED** [review]
Revert whole feature

**Comment by szarnyasg** [comment]
Done. Reverting was not possible as some lines received further edits, so I did it manually.

**Review by Mause — APPROVED** [review]

**Pull request merged**
