### PR TITLE
Replace signbit example to -1.0

### PR DESCRIPTION
**Pull request by Mytherin**

### CODE REVIEW

**Review by carlopi — COMMENTED** [review]
I think this is autogenerated from `src/core_functions/scalar/math/functions.json` in duckdb/duckdb, should it not be changed also there?

**Comment by carlopi** [comment]
Then those are independent, given the one you modified are only old docs that are not autogenerated (I think? unsure).

**Comment by Mytherin** [comment]
This does not only change old docs. But yes it should also be modified upstream.

**Review by carlopi — APPROVED** [review]
Thanks!

**Pull request merged**
