### PR TITLE
document streaming results with jdbc

### LINKED ISSUE #1440: [duckdb/#7327] - JDBC ResultSet consumes unlimited memory needs documentation
See https://github.com/duckdb/duckdb/issues/7327

### PR DESCRIPTION
**Pull request by Mause**
Closes #1440

### CODE REVIEW

**Comment by mustafahasankhan** [comment]
Will the new driver be released with next version or can we make a custom build meanwhile?
Looking forward to it.

**Comment by Mause** [comment]
> Will the new driver be released with next version or can we make a custom build meanwhile?
> Looking forward to it.

You can use the snapshot build in the meantime, documentation is on the installation page

**Comment by mustafahasankhan** [comment]
> > Will the new driver be released with next version or can we make a custom build meanwhile?
> > Looking forward to it.
> 
> You can use the snapshot build in the meantime, documentation is on the installation page

Cannot find the latest jar (duckdb_jdbc-0.10.0-20231025.025423-87.jar) at https://oss.sonatype.org/content/repositories/snapshots/org/duckdb/duckdb_jdbc/0.10.0-SNAPSHOT/

Can you please take a look? It is causing Kotlin gradle project to fail as it tries to find latest.

**Comment by Mause** [comment]
> > > Will the new driver be released with next version or can we make a custom build meanwhile?
> > > Looking forward to it.
> > 
> > 
> > You can use the snapshot build in the meantime, documentation is on the installation page
> 
> Cannot find the latest jar (duckdb_jdbc-0.10.0-20231025.025423-87.jar) at https://oss.sonatype.org/content/repositories/snapshots/org/duckdb/duckdb_jdbc/0.10.0-SNAPSHOT/
> 
> Can you please take a look? It is causing Kotlin gradle project to fail as it tries to find latest.

See https://github.com/duckdb/duckdb/issues/8240

**Pull request merged**
