### PR TITLE
Add CORS tips in s3api

### PR DESCRIPTION
**Pull request by douenergy**
Sometimes, even after correctly setting up all the credentials for an S3 bucket, a browser may not send requests to the S3 bucket. This issue often arises if you haven't set the correct CORS (Cross-Origin Resource Sharing) headers.

Open the [DuckDB WASM Shell](https://shell.duckdb.org/)

### With CORS Header Setting in the Bucket
```sql
FROM 'https://ducket-with-cors-header.s3.ap-northeast-1.amazonaws.com/d1.parquet';
```
### Without CORS Header Setting in the Bucket
```sql
FROM 'https://ducket-without-cors-header.s3.ap-northeast-1.amazonaws.com/d1.parquet';
```

You can download the parquet file directly from both URLs. However, only the bucket with the proper CORS header settings can be queried in the DuckDB WASM.

**We should add tips for setting the CORS header in an S3 bucket.**

截圖 2024-03-07 凌晨12 24 12

### CODE REVIEW

**Comment by douenergy** [comment]
cc @szarnyasg @carlopi  Please Take a Look !

**Comment by douenergy** [comment]
I think the JS client may also encounter this issue (anything involving a browser may need proper CORS settings).

**Comment by Mause** [comment]
> I think the JS client may also encounter this issue (anything involving a browser may need proper CORS settings).

The NodeJS client does not support running in a browser

**Comment by douenergy** [comment]
my bad 😅. Is there any other document where we can add this?

**Comment by carlopi** [comment]
Maybe you can find a way to this page: https://duckdb.org/docs/api/wasm/data_ingestion ?

It's not strictly connected to data ingestion (can happen also with extension loading) BUT it's by far the most common case of wanting to serve some files from S3 for them to be reachable.

Thanks a lot

**Comment by douenergy** [comment]
Thanks @carlopi @Mause  for the reviewing.
I move the tip to [data_ingestion](https://duckdb.org/docs/api/wasm/data_ingestion) httpfs section 

截圖 2024-03-07 下午6 57 34

**Pull request merged**
