### PR TITLE
:gift: Add some csv (parquet) example for HTTPFS :student: 

### PR DESCRIPTION
**Pull request by adriens**
# :grey_question: About

Currently the [`HTTPFS`](https://duckdb.org/docs/extensions/httpfs.html) shows the following documentation : 

image

... but when one runs the script : 

```sql
SELECT * FROM 'https://domain.tld/file.extension';
```

we get this:

image

# :dart: Goal

The goal of this PR (sorry I did not know where to push the `csv` to make it available on `https`) is to provide a fun csv on the web that is under `duckdb's control.

So, currently it can be loaded this way : 

```sql
CREATE OR REPLACE TABLE duckdb_poem AS
    SELECT *
   FROM
   read_csv_auto('duckdb-poem.csv');
```

... and once it will be available on ou `duckdb'`s site, the documentation on HTTPS could become : 

```sql
CREATE OR REPLACE TABLE duckdb_poem AS
    SELECT *
   FROM
   read_csv_auto('https://duckdb.org/docs/data/duckdb-poem.csv');
```

**:point_up: The `parquet`  version could follow the same philosophy**.

:point_right: If it makes sense, and **once I'll know where to push the files, i'll can push the parquet version**.

# :paperclip: Additional resources

- [duckdb_poem.parquet.gz](https://github.com/duckdb/duckdb-web/files/10985645/duckdb_poem.parquet.gz)

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Howdy! Great idea! 

I think the docs github repo is a good place where we could upload those files. Let's use the `data` folder to start!

Here is an example with a csv that already exists in the docs repo, but it is not a fun csv! ;-) To pull data from github, you just have to view it "raw" and then use that url.
```sql
FROM read_csv_auto('https://raw.githubusercontent.com/duckdb/duckdb-web/master/_data/versions.csv', header=TRUE);
```
| version |
|---------|
| 0.7.1   |
| 0.6.1   |
| 0.5.1   |
| 0.4.0   |
| 0.3.4   |
| 0.3.3   |
| 0.3.2   |
| 0.3.1   |
| 0.3.0   |
| 0.2.9   |
| 0.2.8   |

**Comment by adriens** [comment]
@Alex-Monahan 

> Here is an example with a csv that already exists in the docs repo, but it is not a fun csv! ;-

Is it built thgrough CI ?

**Comment by Alex-Monahan** [comment]
Would you be open to adding the files and examples in your PR? I unzipped and opened your parquet file, but it has some odd unicode or maybe newline characters in it that do not render for me on Windows. Could you remove those characters in the file that you upload?

Thanks!

| id |                                 text                                  |
|----|-----------------------------------------------------------------------|
| 1  | In a world of data and code ????                                        |
| 2  | Where information doth explode ????                                     |
| 3  | A database emerged quite new ????                                       |
| 4  | DuckDB, the feathered friend we knew ????                               |
| 5  |                                                                       |
| 6  | With speed and efficiency ????                                          |
| 7  | DuckDB solves queries with agility ???
???                              |
| 8  | A feather-light database to deploy ?????                                |
| 9  | For analytics to enjoy ????                                             |
| 10 |                                                                       |
| 11 | Structured, unstructured, and beyond ????                               |
| 12 | DuckDB stores it all in a bond ??                                      |
| 13 | SQL-compliant, it plays well ??                                        |
| 14 | With other databases, we can tell ????                                  |
| 15 |                                                                       |
| 16 | A mallard in the world of tech ????                                     |
| 17 | DuckDB swims without a peck ???
??                                     |
| 18 | In lakes of data it does wade ????                                      |
| 19 | A quack above the rest is made ?????                                    |
| 20 |                                                                       |
| 21 | So if you seek a database true ????                                     |
| 22 | With power, speed, and charm anew ??????                                 |
| 23 | Look no further than the duck ??                                       |
| 24 | DuckDB, a name you'll love to pluck ????                                |
| 25 |                                                                       |
| 26 | ??  Poem by ChatGPT (Mar 14 Version.) ??????                             |
| 27 | ??  https://help.openai.com/en/articles/6825453-chatgpt-release-notes |

**Comment by Alex-Monahan** [comment]
Hello @adriens! Would you like to take another crack at this without the odd newline characters? Otherwise, I'll go ahead and close it and we can revisit in the future!

**Comment by adriens** [comment]
Hi @Alex-Monahan , 

so you have some issue with emojis at the end of line on you windows ? Even in your IDE :grey_question: 

image

**Comment by Alex-Monahan** [comment]
Ah, emojis... Windows Terminal needs a few changed configs for that. I'll try again and if that works smoothly, sure!

**Comment by adriens** [comment]
Cool let's :crossed_fingers:

**Comment by Alex-Monahan** [comment]
uploading the file first, then we can change the examples

**Comment by adriens** [comment]
That's cool : who takes in charge the example implementation ?

**Pull request merged**
