### PR TITLE
CSV import: I added the stdin mode

### PR DESCRIPTION
**Pull request by aborruso**
It's a precious thing, but still undocumented ( [#4619](https://github.com/duckdb/duckdb/discussions/4619#discussion-4363600) )

### CODE REVIEW

**Comment by Alex-Monahan** [comment]
Hmm, thank you for adding! I think it would make more sense to put it in its own section, as this capability only exists in the CLI, not in the other clients. Or maybe in the CLI doc itself?

**Comment by aborruso** [comment]
> Hmm, thank you for adding! I think it would make more sense to put it in its own section, as this capability only exists in the CLI, not in the other clients. Or maybe in the CLI doc itself?

The title of that file is `CSV Loading`, and that's another way to load a CSV (via stdin).
That's why I entered it here.

But if you prefer I put it in the cli section

**Comment by aborruso** [comment]
And thank you to you @Alex-Monahan !

**Comment by Mytherin** [comment]
Thanks! Looks good to me.

**Comment by aborruso** [comment]
Thank you very much

**Pull request merged**
