### PR TITLE
Another round of extension docs, depends on duckdb/duckdb#9818

### PR DESCRIPTION
**Pull request by carlopi**
This fixes some current inaccuracies and reflect the status post work on custom_extension_repository.

Fixes https://github.com/duckdb/duckdb-web/issues/1670.
Documents duckdb/duckdb#9818.

### CODE REVIEW

**Comment by carlopi** [comment]
Linter result is a mess, haven't properly styled links and all.

**Comment by szarnyasg** [comment]
Thanks, the linter is happy now

**Comment by carlopi** [comment]
> Thanks. I made some changes and the linter is happy now

Thanks!

**Review by szarnyasg — APPROVED** [review]

**Comment by carlopi** [comment]
btw: duckdb/duckdb side has not been merged (yet)

**Comment by szarnyasg** [comment]
Oops. Anyways :-).

**Pull request merged**
