### PR TITLE
Add documentation for list_resize

### PR DESCRIPTION
**Pull request by maiadegraaf**
Adds documentation for list_resize ([PR](https://github.com/duckdb/duckdb/pull/7401))

### CODE REVIEW

**Comment by taniabogatsch** [comment]
Great! Let's wait to merge this until the functionality has landed on the master 😄

**Comment by taniabogatsch** [comment]
This is ready to go :)

**Review by taniabogatsch — APPROVED** [review]

**Comment by Alex-Monahan** [comment]
Would it be possible to make the example self contained? Instead of using `l` for the list, could we use an example list like `[1,2,3]` directly? It's a nitpick, so we can merge without it if desired!

**Comment by maiadegraaf** [comment]
Sure, makes sense to me!

**Comment by Mause** [comment]
Merging this now that feature has been merged to master

**Pull request merged**
