### PR TITLE
docs: updating docs for ca cert and server side verification

### PR DESCRIPTION
**Pull request by pvaezi**

### CODE REVIEW

**Comment by szarnyasg** [comment]
Hi @pvaezi, this particular table is generated automatically from DuckDB using a script:
```md
<!-- This section is generated by scripts/generate_config_docs.py -->
```
So, your changes will be overwritten by the generator. I'd recommend to add these properties elsewhere.

**Comment by szarnyasg** [comment]
Note that I moved the configuration section in #2370

**Comment by pvaezi** [comment]
@szarnyasg thanks for the review, I see the script now. Should I wait for the main PR (https://github.com/duckdb/duckdb/pull/10704) to merge then run the script to generate the md file?

**Comment by szarnyasg** [comment]
@pvaezi yes, the configuration flag will be added to the table once https://github.com/duckdb/duckdb/pull/10704 is merged and in nightly. That said, your are welcome to provide additional documentation on these flags outside of the table.

**Comment by pvaezi** [comment]
> @pvaezi yes, the configuration flag will be added to the table once [duckdb/duckdb#10704](https://github.com/duckdb/duckdb/pull/10704) is merged and in nightly. That said, your are welcome to provide additional documentation on these flags outside of the table.

Ok thanks for the info, that makes sense to avoid parameter documentation drift. I'll incline to close this PR then, unless you'd recommend that those description in the main PR is not sufficient for new expose configurations. Please let me know how to proceed.

**Comment by szarnyasg** [comment]
Sure, let's close this and let the auto-generation take care of it. Thanks!

**Pull request closed without merging**
